(squash me): wip updates to /dragon

diff --git a/dragon b/dragon
--- a/dragon
+++ b/dragon
@@ -49,7 +49,7 @@ fi
 export NINJA_STATUS="\x1b[34m[Dragon] [%f/%t] (%e)"
 
 set -o pipefail
-set -e
+# set -e
 
 function cleanbuildfail()
 {
@@ -58,11 +58,15 @@ function cleanbuildfail()
     echo -e "${PrefixColor}[Dragon]${BoldColor} Build failed${NC}"
     echo -e "${PrefixColor}[Dragon]${BoldColor} Cleaning Up${NC}"
 
-    cd "${project}" || exit 1
-
-    if [ $debug == 1 ]; then
-      python3 $DRAGONBUILD/bin/ninjadebug.py
+    if ! cd "${project:-/nonexist}"; then
+      echo "couldn't get to ${project:-'nill'}"
+      exit 1
     fi
+
+    if (( debug )); then
+      python3 "${DRAGONBUILD}"/bin/ninjadebug.py
+    fi
+
     # a plain `exit` means exit 0 - success
     exit 1
 }
@@ -108,12 +112,13 @@ printBan(){ cat "${DRAGONBUILD}"/internal/banner.txt ; }
 
 setupSSHKey()
 {
+    local ret=0
     echo -e "${PrefixColor}[Dragon]${NC} SSH Passwordless Authentication (RSA Authentication) not configured."
     echo -e "${PrefixColor}[Dragon]${NC} Would you like to do so now? (Y/N)"
     # I guess you __could__ just use python for Y/n prompts
     python3 -c "exit(int('y' in input('> ').lower())^ 1)"
     # shellcheck disable=SC2216
-    local ret=$?
+    ret=$? # 0 == yes
     echo $? | grep "0" > /dev/null || mkdir $DRAGONBUILD/state 2>/dev/null | touch $DRAGONBUILD/state/nosshkey 2>/dev/null | python3 -c 'exit(1)'
     echo $? | grep "1" > /dev/null || echo -e "${PrefixColor}[Dragon]${BoldColor} Copying key [Default password is alpine]:${NC}" 2> python3 -c 'exit(0)'
     echo $? | grep "1" > /dev/null || cat ~/.ssh/id_rsa.pub | ssh -p $DRBPORT root@$DRBIP "mkdir -p ~/.ssh && cat >>  ~/.ssh/authorized_keys" && echo -e "${PrefixColor}[Dragon]${BoldColor} Done${NC}"
@@ -207,66 +212,63 @@ while [ "$1" != "" ]; do
     shift
 done
 
-if [ $debug == 1 ]; then
+declare -rx cwd="$(basename $PWD)"
+
+if (( debug )); then
   NINJA_ARGS="-v"
   export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
-  set -xv
   export DGEN_DEBUG=1
+
+  set -x
 fi
 
-cwd=$(basename $PWD)
-
-
-if [ -f "DragonMake" ]; then
-    gen=1
+if [[ -f "${cwd}/DragonMake" && -f "${cwd}/Makefile" ]]; then
+  gen=1
 else
-    if [ -f "Makefile" ]; then
-        gen=1
-    else
-        python3 ${DRAGONBUILD}/DragonGen/assume.py
-    fi
+  python3 "${DRAGONBUILD}"/DragonGen/assume.py
 fi
 
-if [ -d ".dragon" ]; then
-    true
-else
-    gen=1
+if [[ ! -d "${cwd}/.dragon" ]]; then
+  gen=1
 fi
 
-
-if [ $flutter == 1 ]; then
-    if [ $release == 1 ]; then
-        echo -e "${PrefixColor}[Dragon]${BoldColor} Building with Flutter for iOS (Release)${NC}"
-        flutter build ios
-    else
-        echo -e "${PrefixColor}[Dragon]${BoldColor} Running Flutter${NC}"
-        flutter run
-    fi
+if (( flutter )); then
+  if (( release )); then
+    echo -e "${PrefixColor}[Dragon]${BoldColor} Building with Flutter for iOS (Release)${NC}"
+    flutter build ios
+  else
+    echo -e "${PrefixColor}[Dragon]${BoldColor} Running Flutter${NC}"
+    flutter run
+  fi
 fi
 
-if [ $gen == 1 ]; then
-    rm -rf .dragon/ninja/build.ninja
-    mkdir -p .dragon/ninja > /dev/null
-    mkdir -p .dragon/modules > /dev/null
+if (( gen )); then
+  rm -rf "${cwd}"/.dragon/ninja/build.ninja     || :
+  mkdir -p "${cwd}"/.dragon/ninja   > /dev/null || :
+  mkdir -p "${cwd}"/.dragon/modules > /dev/null || :
 
-    source $DRAGONBUILD/DragonGen/DragonGen $DGEN_DEBUG
+  source "${DRAGONBUILD}"/DragonGen/DragonGen "${DGEN_DEBUG}"
 fi
 
-if [ $build == 1 ]; then
+# this should be a function
+if (( build )); then
     # shellcheck disable=SC2154
-    if [ -z "$project_dirs" ]; then
-        echo "yeet" > /dev/null
-    else
-        projroot=$PWD
-        set -f
+    if [[ -n "${project_dirs}" ]]; then
+        projroot="${PWD}"
+        set -f # disable file-globbing
         subsb=(${project_dirs})
         set +f
-        for i in ${subsb[@]}; do
+        for dir in ${subsb[@]}; do
+            if ! cd "${dir:-/nonexist}"; then
+              echo "couldn't 'cd' into ${dir}"
+              # exit 1
+              # or
+              continue
+            fi
 
-            cd "$i" || exit
-
-            rm -rf .dragon/_
+            rm -rf "${dir}"/.dragon/_ || :
             mkdir -p .dragon/modules
+
             if [ $clean == 1 ]; then
                 if [ $i == "." ]; then
                     echo -e "${PrefixColor}[Dragon]${BoldColor} Cleaning ${TWEAK_NAME}${NC}"
