(squash me): updates towards all bash scripts

diff --git a/dragon b/dragon
--- a/dragon
+++ b/dragon
@@ -1,94 +1,119 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-source $DRAGONBUILD/internal/environment
+: ${DRAGONBUILD:="$(realpath $(dirname ${0}))"}
+if ! source "${DRAGONBUILD}"/internal/environment; then
+  # make me pretty of whatever, we don't have colors yet.
+  printf -- '%s (error): %s\n' "${0}" 'unable to find internal/environment.'
+  printf -- '\t -> DRAGONBUILD is `%s`\n' "${DRAGONBUILD:-"nill"}"
+  exit 1
+fi
+source "${DRAGONBUILD}"/internal/dragoncolors
 
-(bash <(curl -s https://raw.githubusercontent.com/DragonBuild/installer/master/vers) &)
+if ! [[ -n "${DRAGON_SKIP_UPDATE}" ]]; then
+  DRAGON_MASTER_VERSION=$("${DRAGONBUILD}"/internal/check-for-update.sh)
+  if [[ "${DRAGONVERS}" != "${DRAGON_MASTER_VERSION}" ]]; then
+    echo -e >&2 "${GenColor}[Dragon]:" \
+    "${BoldColor} An Update is Avaliable! Install with 'dragon update'. ${NC}"
+  fi
+fi
 
 DBTIMEOUT=5
+options=(
+  'install'
+  'build'
+  'gen'
+  'clean'
+  'export'
+  'only'
+  'norm'
+  'debug'
+  'flutter'
+  'release'
+  #
+  'DRAGON_DPKG'
+)
 
-source $DRAGONBUILD/internal/dragoncolors
+for var in ${options[@]}; do
+  declare -i ${var}=0
+done; unset var
 
-install=0
-build=0
-gen=0
-clean=0
-exportt=0
-only=0
-norm=0
-debug=0
-flutter=0
-DRAGON_DPKG=0
+if command -v dsymutil &>/dev/null; then
+  export ToolchainPath=""
+  export ToolchainPrefix=""
+else
+  export ToolchainPath="${DRAGONBUILD}/toolchain/bin"
+  export ToolchainPrefix=""
+fi
 
-export release=0
-
-ToolchainPath=""
-ToolchainPrefix=""
-command -v dsymutil >/dev/null || export ToolchainPath="${DRAGONBUILD}/toolchain/bin/"; export ToolchainPrefix="";
+# Default prompt for ninja:
+export NINJA_STATUS="\x1b[34m[Dragon] [%f/%t] (%e)"
 
 set -o pipefail
+set -e
 
 function cleanbuildfail()
 {
+    local project="$@"
     # shellcheck disable=SC2154
     echo -e "${PrefixColor}[Dragon]${BoldColor} Build failed${NC}"
     echo -e "${PrefixColor}[Dragon]${BoldColor} Cleaning Up${NC}"
-    cd $1 || exit
+
+    cd "${project}" || exit 1
+
     if [ $debug == 1 ]; then
       python3 $DRAGONBUILD/bin/ninjadebug.py
     fi
-    exit
+    # a plain `exit` means exit 0 - success
+    exit 1
 }
-
-export NINJA_STATUS="\x1b[34m[Dragon] [%f/%t] (%e)"
 
 usage()
 {
-    echo ""
+    echo ####
     echo -e "${PrefixColor}DragonBuild v1.0 ${BoldColor}-=-=-${NC}"
     echo "  usage: dragon [commands]"
-    echo ""
+    echo ####
     echo -e "${PrefixColor}Building ${BoldColor}-=-=-${NC}"
     echo "  d|do - Build and Install"
     echo "  c|clean - recompile, link, and package your project"
     echo "  b|build|make - compile, link, and package your project"
     echo "  r|release - Load DragonRelease file over the DragonMake one"
     echo "  rl|relink - Re-link the package regardless of changes"
-    echo ""
+    echo ####
     echo -e "${PrefixColor}Installation ${BoldColor}-=-=-${NC}"
     echo "  s|device - Set build device IP/Port"
     echo "  i|install - Install to build device"
     echo "  rs|respring - Respring the current build device"
     echo "  dr|devicerun - Run anything after this flag on device"
-    echo ""
+    echo ####
     echo -e "${PrefixColor}Tools ${BoldColor}-=-=-${NC}"
     echo "  exp|export - Tell ninja to create a compile_commands.json"
     echo "  f|flutter - Build with flutter before doing anything else"
     echo "  ch|checkra1n - Open Checkra1n GUI"
     echo "  chc|checkra1ncli - Open Checkra1n CLI"
-    echo ""
+    echo ####
     echo -e "${PrefixColor}Debugging ${BoldColor}-=-=-${NC}"
     echo "  vn - Print clang/ld/etc. commands and flags"
     echo "  vd - echo every bash command in the main dragon file"
     echo "  vg - DragonGen verbositiy."
     echo "  norm - Doesn't delete build.ninja after building."
     echo "  debug - Enable all debug flags"
-    echo ""
+    echo ####
     echo -e "${PrefixColor}-=-=-${NC}"
-    echo ""
+    echo ####
     echo "DragonBuild v1.0.0 - by kritanta"
 }
 
-printBan()
-{
-    cat $DRAGONBUILD/internal/banner.txt                                             
-}
+printBan(){ cat "${DRAGONBUILD}"/internal/banner.txt ; }
 
 setupSSHKey()
 {
     echo -e "${PrefixColor}[Dragon]${NC} SSH Passwordless Authentication (RSA Authentication) not configured."
     echo -e "${PrefixColor}[Dragon]${NC} Would you like to do so now? (Y/N)"
+    # I guess you __could__ just use python for Y/n prompts
     python3 -c "exit(int('y' in input('> ').lower())^ 1)"
     # shellcheck disable=SC2216
+    local ret=$?
     echo $? | grep "0" > /dev/null || mkdir $DRAGONBUILD/state 2>/dev/null | touch $DRAGONBUILD/state/nosshkey 2>/dev/null | python3 -c 'exit(1)'
     echo $? | grep "1" > /dev/null || echo -e "${PrefixColor}[Dragon]${BoldColor} Copying key [Default password is alpine]:${NC}" 2> python3 -c 'exit(0)'
     echo $? | grep "1" > /dev/null || cat ~/.ssh/id_rsa.pub | ssh -p $DRBPORT root@$DRBIP "mkdir -p ~/.ssh && cat >>  ~/.ssh/authorized_keys" && echo -e "${PrefixColor}[Dragon]${BoldColor} Done${NC}"
@@ -129,7 +154,7 @@ while [ "$1" != "" ]; do
                                 ;;
         g | gen | generate)     gen=1
                                 ;;
-        n | nic | new)          python3 $DRAGONBUILD/bin/nic.py  
+        n | nic | new)          python3 $DRAGONBUILD/bin/nic.py
                                 exit
                                 ;;
         exp | export)           exportt=1
@@ -192,17 +217,17 @@ fi
 cwd=$(basename $PWD)
 
 
-if [ -f "DragonMake" ]; then  
+if [ -f "DragonMake" ]; then
     gen=1
 else
     if [ -f "Makefile" ]; then
         gen=1
-    else 
+    else
         python3 ${DRAGONBUILD}/DragonGen/assume.py
     fi
 fi
 
-if [ -d ".dragon" ]; then  
+if [ -d ".dragon" ]; then
     true
 else
     gen=1
@@ -219,44 +244,44 @@ if [ $flutter == 1 ]; then
     fi
 fi
 
-if [ $gen == 1 ]; then 
-    rm -rf .dragon/ninja/build.ninja 
+if [ $gen == 1 ]; then
+    rm -rf .dragon/ninja/build.ninja
     mkdir -p .dragon/ninja > /dev/null
     mkdir -p .dragon/modules > /dev/null
 
     source $DRAGONBUILD/DragonGen/DragonGen $DGEN_DEBUG
 fi
 
-if [ $build == 1 ]; then 
+if [ $build == 1 ]; then
     # shellcheck disable=SC2154
     if [ -z "$project_dirs" ]; then
-        echo "yeet" > /dev/null 
-    else 
+        echo "yeet" > /dev/null
+    else
         projroot=$PWD
         set -f
         subsb=(${project_dirs})
-        set +f 
+        set +f
         for i in ${subsb[@]}; do
 
             cd "$i" || exit
 
             rm -rf .dragon/_
             mkdir -p .dragon/modules
-            if [ $clean == 1 ]; then 
-                if [ $i == "." ]; then 
+            if [ $clean == 1 ]; then
+                if [ $i == "." ]; then
                     echo -e "${PrefixColor}[Dragon]${BoldColor} Cleaning ${TWEAK_NAME}${NC}"
                 else
-                    if [ $only == 1 ]; then 
+                    if [ $only == 1 ]; then
                         true;
                     fi
                     echo -e "${PrefixColor}[Dragon]${BoldColor} Cleaning ${i}${NC}"
                 fi
-                rm -rf .dragon/build 
+                rm -rf .dragon/build
                 rm -rf .dragon/obj
                 rm -rf .dragon/hash
                 rm -rf .dragon/sign
             fi
-            if [ $i == "." ]; then 
+            if [ $i == "." ]; then
                 echo -e "${PrefixColor}[Dragon]${BoldColor} Building ${TWEAK_NAME}${NC}"
             else
                 echo -e "${PrefixColor}[Dragon]${BoldColor} Building ${i}${NC}"
@@ -264,14 +289,14 @@ if [ $build == 1 ]; then
             env $'NINJA_STATUS=\x1b[1;34m[Dragon] \x1b[35m[%f/%t] \x1b[34m(%e)\x1b[0m ' CLICOLOR_FORCE=1 ninja -j17 $NINJA_ARGS || cleanbuildfail $projroot
             env $'NINJA_STATUS=\x1b[1;34m[Dragon] \x1b[34m>>>\x1b[0m ' CLICOLOR_FORCE=1 ninja -j9 stage $NINJA_ARGS || echo -e "${PrefixColor}[Dragon]${BoldColor} No Stage Commands ${NC}"
 
-            if [ $exportt == 1 ]; then 
+            if [ $exportt == 1 ]; then
                 echo -e "${PrefixColor}[Dragon]${BoldColor} Generating compile_commands.json ${NC}"
                 ninja -t compdb "$(awk '/^rule (C|CXX)_COMPILER__/ { print $2 }' build.ninja)" > compile_commands.json
             fi
             if [ $norm == 0 ]; then
                 mkdir .dragon/ninja 2>/dev/null && mv build.ninja .dragon/ninja/build.ninja
             fi
-            if [ $i == "." ]; then 
+            if [ $i == "." ]; then
                 true;
             else
                 cp -R .dragon/_ "$projroot"/.dragon
@@ -345,7 +370,7 @@ if [ $install == 1 ] && [ $DRAGON_DPKG == 1 ]; then
     echo -e "${PrefixColor}[Dragon]${BoldColor} Copying package to device and running install commands${NC}"
 
     scp -P $DRBPORT packages/${OUTPUT} root@$DRBIP:/var/mobile/${OUTPUT} || exit && ssh -p $DRBPORT root@$DRBIP "dpkg -i /var/mobile/${OUTPUT}" || exit && ssh -p $DRBPORT root@$DRBIP "rm -rf /var/mobile/${OUTPUT}"
-    
+
     echo -e "${PrefixColor}[Dragon]${BoldColor} Running '${INSTALL_CMD}' ${NC}"
     ssh -p $DRBPORT root@$DRBIP "${INSTALL_CMD}" || exit
 fi
